shared:
  image: node:20
  # settings:
  #   slack:
  #     channels:
  #       - slack-test1
  #     statuses:
  #       - SUCCESS
  #       - FAILURE
  #       - QUEUED
  #       - RUNNING
  #     minimized: false
jobs:
  main:
    # annotations:
    #   screwdriver.cd/buildPeriodically: H * * * *
    requires: [ ~pr, ~commit ]
    steps:
      - echo hello
